### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by Kartik2016** [gparlakov/scuri#103]
Hi! @gparlakov I want to use Scuri to automate test case generation for react web apps in my organization. Can Scuri be used with react apps? If no, is there any other tool that you would recommend? In case the answer to both of the questions is no, where can i get a code tour of scuri so that i can understand it and can modify or write something of my own that would work with react!
Thanks

**Comment by gparlakov** [comment]
Hi @Kartik2016, glad to see you've found my project.

Unfortunately it is as you say no to both questions.

Scuri uses Schematics  (Angular specific project) to generate and update the specs.

I would be interested to take part in a project to port Scuri to React. We can replace Schematics with some react specific or generic code generator. Scuri has hard dependency on multiple Angular specific libraries and types of doing things.

That said, some of the typescript class and function parsing code can be reused.

I believe in the utility of such a a project for the react community.

What do you think?

**Comment by Kartik2016** [comment]
Thank you for such a prompt response!

Yes i feel such a project would benefit the ever so growing React Community. I haven't been able to find something with this functionality.

I am interested in working on a port for React. I work in the Indian Time zone (IST). Lets do our research about what can be done and connect over the weekend?

**Comment by gparlakov** [comment]
Hey,

This weekend is pretty busy for me. Let me reach out after that. Thanks!

**Comment by manudss** [comment]
Hello, 

I my fork of Scuri : 
https://github.com/manudss/scuri/tree/feature/analyse-content-of-class-wip

 I have begening to implement some change. And one was the possibility to specify a type for generated a test. This was a different template to generate the test.  For exemple to generate a test, in the way of Angular, with Testbed Function : 

`yarn run s .:spec --name example/angular-6-app-jest/src/app/app.component.ts --force --dry-run false --type testbedD`

This will use this template : https://github.com/manudss/scuri/blob/feature/analyse-content-of-class-wip/src/spec/files/testbed/__specFileName__.template 

This could be a first approach, to have a type of generation for React. 

Then I also continued to work on a better interpretation of the TS class, to generate more complete files, for example, with function parameters. 

Then, I didn't have time to continue, so I'm more up to date, but this could be a basis.

**Comment by Kartik2016** [comment]
@gparlakov Sure I'll wait.
@manudss Thanks a lot for the input! I'll have a look at it

**Comment by gparlakov** [comment]
@Kartik2016 
So SCuri works this way:
 - uses [schematics](https://www.npmjs.com/package/@angular-devkit/schematics-cli) : `schematics scuri:spec --name my-file.ts` 
 - schematics CLI is not really Angular specific - so that's **not blocking** for **React** support
 - then using typescript, it reads and parses the file specified by `--name` so that it can get 
     - class name
     - class parameters
     - class public methods
     - function name (if there is no class in the given file)
- using those parameters it creates a spec file:
     -`describe "name-of-class"` 
     - `it` test case for each of the public methods
     - a `setup` function which creates and supplies the unit-under-test and its dependencies (this is really important in Angular)
- having this structure (the describe, it and setup) SCuri can also handle maintenance when there's:
    - new method in the class
    - new dependency in the class 

It looks like it can be used for React components using Class-es too. Not sure about functions.

So, have you tried to `schematic scuri:spec --name my-react.component.ts`? What happens?

**Comment by Kartik2016** [comment]
Hi @gparlakov Yes schematics works with React too. By running the command for a react component I was able to generate spec file. I may need to make a few tweaks to suit my needs for which i'll probably create a patch. I'll post if anything else comes up. Thanks

**Comment by gparlakov** [comment]
@Kartik2016 Did you try out [SCuri-code](https://marketplace.visualstudio.com/items?itemName=gparlakov.scuri-code) - the extension for VS Code?

**Comment by Kartik2016** [comment]
Hi @gparlakov Yes i did. I was not able to run the update command properly through the extension, but the command works perfectly

**Comment by gparlakov** [comment]
@Kartik2016 if you still experience errors with using the extension could you perhaps [open an issue](https://github.com/gparlakov/scuri-code/issues)?  
Perhaps add error output and/or a repro repository...
