### ISSUE TITLE
First letter Shorthand error

### ISSUE THREAD

**Issue by danielberebel** [gparlakov/scuri#108]
I have minor issue related to shorthand by class first letter, when update (fine on create) specs files.
It works unequal on declare build class and use declaration.

For exemple on my  ProductDetailsComponent it generates this code:
`
it('when ngOnInit is called it should', () => {
        // arrange
        const { build } = setup().default();
        const p = build();
        // act
        c.ngOnInit();
        // assert
        // expect(c).toEqual
    });
`

On declare build results it works properly but not on calls methods and do "expect" that use old shorthand based on file type.

Thanks

**Comment by gparlakov** [comment]
Hi, thanks for reaching out. Will try to fix this as soon as possible!

**Comment by gparlakov** [comment]
@danielberebel hi, try 1.0.6 - should work now
