### ISSUE TITLE
Update should use classTemplate if provided

### ISSUE THREAD

**Issue by danjor** [gparlakov/scuri#128]
Current behavior :
When providing update argument with classTemplate, the custom template is not being used.

Update should use classTemplate if provided.

This would also allow to use TestBed instead of adding a setup function.

**Comment by gparlakov** [comment]
Update is not supported with the class template. Update would need a
individual spec and setup templates and perhaps others.

It seems that  using TestBed is something you'd prefer, is that correct?

**Comment by danjor** [comment]
Thank you for your anwser.

Yes, I'd like to have TestBed instead of setup function.
I also need to use autoSpy from jasmine-auto-spies npm package.
I also have a waitForAsync in beforeEach.

So, for create, I use a custom class template to have something like bellow :

```typescript
beforeEach(
    waitForAsync(() => {
      TestBed.configureTestingModule({
        providers: [SanitizeInputDirective,
             provideAutoSpy(MyService)
        ]
      });

      directive = TestBed.inject(MyDirective);
      myServiceSpy = spyInject<MyService>(TestBed.inject(MyService));
    })
  );
```
And I would like to have the update to be able to work with this kind of created spec.

**Comment by gparlakov** [comment]
That's an interesting challenge. Already looking into it and will give updates.

**Comment by gparlakov** [comment]
Hey @danjor 

There is an experimental version that you can try by `npm i scuri@1.2.0-rc-custom-update-2`
OR in your browser right now at - [https://stackblitz.com/edit/node-begvxc?file=result.ts.template](https://stackblitz.com/edit/node-begvxc?file=result.ts.template)

The custom class template needs 2 additions

- markers where the updates should happen , e.g.: 
   - `// scuri:lets` or
   - `// scuri:injectables` 
- templates for each marker to use on update, e.g.: 
    - ```
      /** scuri:template:lets:<%params.forEach(p => {%>let <%= camelize(p.type) %>Spy: <%= p.type %>;
<% }) %>*/
      ```
Follow these steps to try it out:
- add markers and templates 
- add new deps and/or public methods
- run `npx schematics scuri:update-custom --name example.ts --classTemplate=result.ts.template` (change --name and --classTemplate accordingly)

![image](https://user-images.githubusercontent.com/3482199/140623410-c39f598f-794a-418b-b799-b06195510b71.png)
![image](https://user-images.githubusercontent.com/3482199/140623415-d4a1b775-f498-406d-9b6f-1a40775c2d92.png)

**Comment by danjor** [comment]
Thank you for your quick feedback and new version ! :)
It seems to work as expected for the first tries.

I notice you are using "shorthand" for the variable name for the component that is being tested.
This variable name in reality get only the first character of the component name 
e:i MyComponent -> m
I would prefer to have this for the variable name : myComponent

For this, I just tried to replace the usage of shorthand by varName :

by
<% var varName; %><% varName = className[0].toLowerCase() + className.substring(1) %>
and use it varName:

    <%= varName %>.<%= meth %>();

But, when creating spec, then adding some methods and calling update, methods didn't get updated anymore.

So, could it be possible to set shorthand with className[0].toLowerCase() + className.substring(1)  instead ?

Also, if trailing coma get remove for the last provider, and update is run, generator will think that the provider is not already there and add it again.

**Comment by gparlakov** [comment]
For the name you can use the camelize function that is available in the
template environment. So <%= camelize(className) like it's used in the lets
template...

Not sure what to do about the trailing comma... Removing the last character
when de-duplicating  feels arbitrary and error prone... Let me think about
it for a while

**Comment by gparlakov** [comment]
About the `<%= var  %>` it seems to work on my end - [link](https://stackblitz.com/edit/node-yy3fso?file=example.spec.ts)

Original code of the templating engine: 
https://github.com/angular/angular-cli/blob/37a06a7c37f5b4286d58b475e6e12c86f00fac5b/packages/angular_devkit/core/src/utils/template.ts#L216-L217

**Comment by danjor** [comment]
I had the following that was working :

```
/** scuri:template:methods-skipDeDupe:<% publicMethods.forEach(meth=> {if(meth != '') { %>it('when <%= meth %> is called it should', () => {
    // <-- To replace with your Given Description : lets and spies -->
    <%= camelize(className) %>.<%= meth %>();
    // <-- To replace with your Then Description : expects-->
    // expect(<%= shorthand %>).toEqual
});
<% }}) %>*/
```

if I replace <%= shorthand %> by <%= camelize(className) %>, I now have an error saying "className is not defined".
maybe the template engin cannot access some variable.

UPDATE :
-> finally here I use camelize(**name**) and it's working as expected as name is part of ClassDescription.
-> and ousite template I use camelize(**className**)

**Comment by gparlakov** [comment]
It seems `className` was not exposed

@danjor thanks - I'll be sure to expose the same variables with the same names to the create and update templates.

**Comment by gparlakov** [comment]
@danjor a release candidate version https://www.npmjs.com/package/scuri/v/1.2.0-rc-4 with 
- custom template updates 
- exposing string functions like `dasherize` and `classify` [from angular](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/utils/strings.ts) 
- support for custom naming of the custom template like `__name@dasherize__.custom-spec.ts.template`

**Comment by gparlakov** [comment]
> Also, if trailing comma get removed from the last provider, and update is run, generator will think that the provider is not already there and add it again.

I guess there is a linting/prettier-like tool that is smart and removes the trailing comma?

**Comment by danjor** [comment]
Thanks! 

Yes, that's the issue I get.
I run the scuri schematic a first time.
It creates a spec file will all the providers. 
Then, I commit, and a pre-commit hook will run prettier on staged files and remove trailing comma.
Then, I run the scuri command again, and I get the last provider added again to the spec file because the trailing comma got remove previously.

**Comment by gparlakov** [comment]
@danjor this seems to be a common use case and I wanted to handle it "in" scuri but there are a lot of cases and a lot of tools. 

What I can suggest is looking at 2 options of controlling the tools at your particular tool
- **disable the tool** for a particular part of the code - [example for prettier](https://prettier.io/docs/en/ignore.html#javascript)
- let the tool do its job and **arrange** the **template** so the lines stay:
    - In this case it seems placing the **comma at the start** of the line does the trick - see [scuri rc 4 online](https://stackblitz.com/edit/scuri-1-2-0-rc-4?file=example.spec.ts) and run ` npx schematics scuri:spec --name example.ts --update --classTemplate=__specFileName__.template` 
    - ![image](https://user-images.githubusercontent.com/3482199/142807830-d25fd1cb-292a-4194-a73b-67587f029fc0.png)

**Comment by danjor** [comment]
Thanks for your suggestions and examples, I'll check that.

**Comment by danjor** [comment]
I finally moved the provided of the class being tested at the end of providers, without appending a comma at the end of line for this one. This way, no more  issue because there is no more trailing coma.

**Comment by gparlakov** [comment]
[1.2.0 released](https://www.npmjs.com/package/scuri/v/1.2.0)

**Comment by gparlakov** [comment]
@all-contributors please add @danjor for bugs
