### ISSUE TITLE
classTemplate doesn't work as expected in release 1.2.0

### ISSUE THREAD

**Issue by danjor** [gparlakov/scuri#137]
Hello,

I just upgraded from version 1.2.0-rc-custom-update-2 to 1.2.0, and it seems that at least the create spec file using classTemplate param is broken.

Indeed, running the schematic simply copy de template file in the TS file folder, without replacing the content and without renaming it.

**Comment by gparlakov** [comment]
Hi, @danjour.

I'll look into it ASAP.

In the meantime, can you try a clean install (as I've changed the layout of
the whole package thereight be some code mixing)?

**Comment by gparlakov** [comment]
I can't seem to reproduce. 

I seem to remember happening is If the template name did not end in `.template` or was using some invalid parameters/function calls ended up copying the template....

Make sure the template ends in `.template` and is valid - use some of the (examples)[https://gist.github.com/gparlakov/f299011829e229c9d37cf0cb38506d97]

**Comment by gparlakov** [comment]
@danjor here's a place online where we can try to reproduce your issue and fix it [https://stackblitz.com/edit/scuri-1-2-0-issue-134?file=example.md](https://stackblitz.com/edit/scuri-1-2-0-issue-134?file=example.md) 

Try and reproduce it there and get back to me. (see example.md file with examples of create and update commands)
![image](https://user-images.githubusercontent.com/3482199/143385033-46c054e9-7e95-4578-8796-f44b9728c7ba.png)

**Comment by danjor** [comment]
Hi @gparlakov 
Thanks for your replies again :)

Effectively, even if you previously talked about this, I missed that point about some changes that have been done for the naming of custom template in version 1.2.0

My custom template was named spec.tmpl.
So by renaming it with **__specFileName__.template** that effectively work as expected.
So there is no issue in fact.
