### ISSUE TITLE
Abstract classes

### ISSUE THREAD

**Issue by tziyang-lum** [gparlakov/scuri#52]
First of all, thanks for the great tool, much appreciate it. I do got some issue though. I have few abstract components that I also want to test, but when I run ng test it gives an error at the build function: `Cannot create an instance of an abstract class.ts(2511)`. I could make a new class and extend it with this component. This will solve the issue, but maybe there is an other way? 

Secondly, is it possibly to generate the spec files through scanning a directory?  Just like the angular-spec-generator package.

**Comment by gparlakov** [comment]
Hi @tziyang-lum, glad you like the tool and appreciate the time you took to provide feedback.

#### Abstract class 
You are right about having to implement the abstract class (component), but did you know TS actually allows for in-place implementation of an abstract class?
```ts
abstract class MyComponent {
    abstract doStuff(): number;
}

const c = new class extends MyComponent {
    doStuff(): number {
        return 42;
    }
}
```

#### Folder batching
Please correct me if I am wrong, you'd like to give the tool a **folder** full of `.ts` **files** and let it generate the `.spec.ts` for them?

This seems like a once per app thing and I would create a separate script for it. It will 
 - gather all `.ts` files 
 - exclude `.spec.ts` 
 - call `scuri create` for `.ts` with no `.spec.ts.` yet
 - call `scuri update` for the ones with `.spec.ts` 

Thing is that SCuri does not produce all ready specs, it gets you almost there, but a person needs to take care of formatting, importing stuff missed by the tool. And I would imagine having to do this on a batch of 50 files will get old real quick.

How does this sound?

**Comment by tziyang-lum** [comment]
Hello @gparlakov, thanks for the fast reply!

**Abstract class:** Nice,I haven't thought about this implementation. This is better than creating new test classes. 

**Folder batching**: You are correct, I want to have a tool that search every .ts file through a folder. Now I need to type the SCuri script for each path and that will take some time for me to implement it to the project where I am working on. I would like to have a script what you have mentioned about gathering the .ts files and creating/updating the .spec.ts files. 

I'm sorry, but I do not understand about the part that will get old quick if this script is running on a batch of 50 files. 

Thanks again for the quick response and help!

**Comment by gparlakov** [comment]
@tziyang-lum about the 50 files, the scenario is the following. 
 * there is this feature **batch create** where SCuri takes a bunch of files and spits out the specs
 * these specs are not production-ready - a person needs to actually look at each one in turn 
 * that's where the "getting old" thing comes in - I would not want to be the person that traverses 50 (or 100, 500) spec files and decides for each one what needs to be tested, what needs to be commented out, etc.

So what do you think, is it ridiculous to can close this issue?
