### ISSUE TITLE
Calls method of service in component doesn't work

### ISSUE THREAD

**Issue by fgisslen** [gparlakov/scuri#54]
Hi,
I created a test of a component with scuri.
The component calls a service function in the constructor. 

When the test tries to build it get's the error: TypeError: this.authService.loggedIn is not a function.

Does anyone have a clue on why this is happening?

**Comment by ETJ9914** [comment]
As this was closed was there a solution or has it just been moved to the new issue that in mentioned above? As I am facing the same problem and wondered if there was something I missed.

**Comment by gparlakov** [comment]
Workaround was to replace 'Object.keys' with 'Object.getOwnPropertyNames'
in auto-spy.ts.

Not yet had the chance to look into the reason why Object.keys does not
work.
