### ISSUE TITLE
file missing or empty

### ISSUE THREAD

**Issue by jesseboydgsa** [gparlakov/scuri#99]
in vs code i open terminal in directory of ts file I want to build spec for.
doing bash 'ls' shows the x.ts file i want to test
$ ng g scuri:spec --name x.ts  (in same directory of x.ts)

error message:  Params: name: x.ts update: false
            The file x.ts is missing or empty.
Nothing to be done.

The file is there, what can I do?

**Comment by gparlakov** [comment]
Hi @jesseboydgsa,
Have you tried relative path? --name ./x.ts

**Comment by jesseboydgsa** [comment]
yes i've tried relative, bash window even autocompletes the name for me so I know the file is reached...  but still says file missing or empty :(

**Comment by gparlakov** [comment]
I see. Let me try and reproduce the issue and get back to you.

**Comment by gparlakov** [comment]
It occurred to me that 'ng' assumes an Angular project and expects to see a
folder structure of ./scr/app. Hence the x.ts would be interpreted as
./src/app/x.ts

Much like doing `ng g c my` results in a
./src/app/my-component/my-component.ts

**Comment by jesseboydgsa** [comment]
the vs code extension does work for me but not my colleague (maybe because he installed cli first and i started with vs code ext) so we then tried the cli method.  

vs code extension log shows something like this --name "apps/proj/src/app/project1/subfolder/a.service.ts"  when i use vs code create spec with SCuri after highlighting a.service.ts

also note we are micro front end architecture using Nx workspace.  anyway it would be nice if the code would be aware of it's current directory when you run the command.

**Comment by gparlakov** [comment]
Code extensions uses schematics CLI so it does 'schematics scuri:spec
--name absolute path to file'

Maybe I can help with your colleague's issue with the extension?

**Comment by gparlakov** [comment]
@jesseboydgsa how did you end up handling the issue?
